version: '3.4'

volumes:
  cache:
  log:

services:
  app:
    ports:
      - 80:80
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/sources/app/public
    build:
      context: .
    volumes:
      - .:/var/www/html/sources
      - ./config/vhost.conf:/etc/apache2/sites-available/000-default.conf
     # - cache:/var/www/html/sources/app/var/cache
      #- log:/var/www/html/sources/app/var/log
#    db:
#      ports: [5432]
#      labels:
#        com.symfony.server.service-prefix: 'DATABASE'